'use client';
import {useEffect,useState} from 'react';
type MarketAsset={code:string;name:string;type:string};
export type TeamEditData={user:{email:string};team:{id:string;name:string;season:number};snapshot:{grandPrix:{round:number};cashBalance:number|null;freeTransfers:number|null;totalPoints:number|null;assets:(MarketAsset&{isDoubled:boolean})[];chips:{code:string;status:string}[]}};
export default function TeamEditor({data,onSaved,onCancel}:{data:TeamEditData;onSaved:()=>Promise<void>;onCancel:()=>void}){
 const [name,setName]=useState(data.team.name),[cash,setCash]=useState(data.snapshot.cashBalance==null?'':String(data.snapshot.cashBalance)),[free,setFree]=useState(data.snapshot.freeTransfers==null?'':String(data.snapshot.freeTransfers)),[points,setPoints]=useState(data.snapshot.totalPoints==null?'':String(data.snapshot.totalPoints));
 const [drivers,setDrivers]=useState(Array.from({length:5},(_,i)=>data.snapshot.assets.filter(a=>a.type==='DRIVER')[i]?.code||''));const [constructors,setConstructors]=useState(Array.from({length:2},(_,i)=>data.snapshot.assets.filter(a=>a.type==='CONSTRUCTOR')[i]?.code||''));const [doubled,setDoubled]=useState(data.snapshot.assets.find(a=>a.isDoubled)?.code||'');
 const [chips,setChips]=useState<Record<string,string>>(()=>Object.fromEntries(['WC','LL','AP','NN','DRS','FF'].map(code=>[code,data.snapshot.chips.find(c=>c.code===code)?.status||'UNKNOWN'])));
 const [market,setMarket]=useState<MarketAsset[]>(data.snapshot.assets);const [busy,setBusy]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{let active=true;fetch('/api/market?season='+data.team.season+'&round='+data.snapshot.grandPrix.round).then(async r=>{const j=await r.json();if(!r.ok||!Array.isArray(j.assets))throw Error('Market unavailable.');if(active)setMarket([...j.assets,...data.snapshot.assets.filter(a=>!j.assets.some((m:MarketAsset)=>m.code===a.code&&m.type===a.type))])}).catch(()=>{if(active)setStatus('Other market assets are unavailable. You can still edit your current picks and status.')});return()=>{active=false}},[data]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setStatus('');try{
  const assets=[...drivers.map(code=>({code,type:'DRIVER',isDoubled:code===doubled})),...constructors.map(code=>({code,type:'CONSTRUCTOR',isDoubled:false}))];
  const r=await fetch('/api/team/manage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({teamId:data.team.id,name,round:data.snapshot.grandPrix.round,assets,cashBalance:cash===''?null:Number(cash),freeTransfers:free===''?null:Number(free),totalPoints:points===''?null:Number(points),chips})});const j=await r.json();if(!r.ok)throw Error(j.error||'Save failed.');await onSaved();
 }catch(e){setStatus(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 const select=(type:string,value:string,change:(value:string)=>void,onlyPicked=false)=><select aria-label={onlyPicked?"2× driver":undefined} required value={value} onChange={e=>change(e.target.value)}><option value="">Select…</option>{market.filter(a=>a.type===type&&(!onlyPicked||drivers.includes(a.code))).map(a=><option key={a.type+a.code} value={a.code}>{a.code} · {a.name}</option>)}</select>;
 return <form onSubmit={save}><h3>Edit team</h3><p>Edits apply to your Paddock IQ team. A later F1 import replaces them with F1 data.</p><fieldset disabled={busy}><div className="inputs"><label>Team name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Cash ($M)<input type="number" min="0" max="999999.99" step="0.01" value={cash} onChange={e=>setCash(e.target.value)}/></label><label>Free transfers<input type="number" min="0" step="1" value={free} onChange={e=>setFree(e.target.value)}/></label><label>Total points<input type="number" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label></div>
 <h4>5 drivers</h4>{drivers.map((value,i)=><label key={i}>Driver {i+1}{select('DRIVER',value,code=>{const next=[...drivers];next[i]=code;setDrivers(next);if(!next.includes(doubled))setDoubled('')})}</label>)}<label>2× driver{select('DRIVER',doubled,setDoubled,true)}</label>
 <h4>2 constructors</h4>{constructors.map((value,i)=><label key={i}>Constructor {i+1}{select('CONSTRUCTOR',value,code=>{const next=[...constructors];next[i]=code;setConstructors(next)})}</label>)}
 <h4>Chips</h4><div className="inputs">{Object.entries(chips).map(([code,status])=><label key={code}>{code}<select value={status} onChange={e=>setChips({...chips,[code]:e.target.value})}>{['AVAILABLE','USED','LOCKED','UNKNOWN'].map(s=><option key={s}>{s}</option>)}</select></label>)}</div><p><button type="submit">Save changes</button> <button type="button" onClick={onCancel}>Cancel</button></p></fieldset><p role="status">{busy?'Saving…':status}</p></form>
}
