import {writeFile} from 'node:fs/promises';
import {forecast,score} from './backtest-component-calibration';
const mean=(xs:number[])=>xs.reduce((a,b)=>a+b,0)/xs.length;
type Candidate={family:string;conditional:boolean;raceNoise?:number;qualifyingNoise?:number;progress:boolean;halfLife?:number;driverPrior?:number};
const predict=(round:number,c:Candidate)=>forecast(round,undefined,undefined,3,undefined,c.conditional,c.qualifyingNoise,0,c.raceNoise,c.progress,{halfLife:c.halfLife,driverPrior:c.driverPrior});
function summarize(rows:ReturnType<typeof forecast>){const d=rows.filter(r=>r.type==='DRIVER');return {...score(rows),overtakesMAE:mean(d.map(r=>Math.abs(r.components.overtakes-r.observed.race!.overtakes))),positionsMAE:mean(d.map(r=>Math.abs(r.components.positions-r.observed.race!.positionChange)))}}
async function main(){
 const development=[6,7,8,9,10,11],later=[12,13,14,15,16];const current:Candidate={family:'current',conditional:false,progress:false};const base=summarize(development.flatMap(round=>predict(round,current)));const candidates:any[]=[];
 for(const family of [{family:'current-rankings',raceNoise:undefined,qualifyingNoise:undefined,progress:false},{family:'historical-race-pace',raceNoise:.15,qualifyingNoise:undefined,progress:false},{family:'grid-progress',raceNoise:0,qualifyingNoise:.15,progress:true}])for(const halfLife of [undefined,1,2,4,8])for(const driverPrior of [undefined,1,5,10]){const c:Candidate={...family,conditional:true,halfLife,driverPrior};const s=summarize(development.flatMap(round=>predict(round,c)));const eligible=s.DRIVER.MAE<=base.DRIVER.MAE&&s.CONSTRUCTOR.MAE<=base.CONSTRUCTOR.MAE&&s.positionsMAE<=base.positionsMAE&&s.overtakesMAE<=base.overtakesMAE;candidates.push({...c,...s,eligible})}
 candidates.sort((a,b)=>a.objective-b.objective);const eligible=candidates.filter(c=>c.eligible);const selected:Candidate=eligible[0]??current;const bestOvertakes:Candidate=[...candidates].sort((a,b)=>a.overtakesMAE-b.overtakesMAE)[0];
 const report:any={baselineVersion:'constructor component25-v3 / driver component25-v2',note:'Exploratory on reused rounds, not fresh validation. Only development rounds select settings. Weighting affects overtake count fitting and failed-race mean, not qualifying/race pace histories. Passing metrics can include Monte Carlo variation in unchanged ranking components; no production activation.',developmentRounds:development,evaluationRounds:later,baselineDevelopment:base,selected,eligibleCount:eligible.length,bestOvertakes,candidates,metrics:[],byRound:[]};
 for(const [segment,rounds] of [['development',development],['previously-inspected',later]] as const)for(const [model,c] of [['current',current],['selected-with-gate',selected],['best-overtakes-diagnostic',bestOvertakes]] as const){const rows=rounds.flatMap(round=>predict(round,c));const s=summarize(rows);for(const type of ['DRIVER','CONSTRUCTOR'] as const)report.metrics.push({segment,model,type,...s[type],...(type==='DRIVER'?{overtakesMAE:s.overtakesMAE,positionsMAE:s.positionsMAE}:{})});for(const round of rounds)report.byRound.push({segment,model,round,...summarize(rows.filter(r=>r.round===round))})}
 console.log('Eligible candidates:',eligible.length);console.table(candidates.slice(0,12).map(c=>({family:c.family,halfLife:c.halfLife,prior:c.driverPrior,eligible:c.eligible,driverMAE:c.DRIVER.MAE,constructorMAE:c.CONSTRUCTOR.MAE,overtakesMAE:c.overtakesMAE,positionsMAE:c.positionsMAE})));console.table(report.metrics);await writeFile('docs/recent-overtakes-results.json',JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1});
