import {writeFile} from 'node:fs/promises';
import {forecast,score} from './backtest-component-calibration';
const mean=(xs:number[])=>xs.reduce((a,b)=>a+b,0)/xs.length;
type Candidate={name:string;gridRelative:boolean;raceNoise?:number;qualifyingNoise?:number;conditional:boolean;reliability:boolean};
const predict=(round:number,c:Candidate)=>forecast(round,c.reliability?16:undefined,c.reliability?16:undefined,3,c.reliability?'reliability-dotd-pits':undefined,c.conditional,c.qualifyingNoise,0,c.raceNoise,c.gridRelative);
function summarize(rows:ReturnType<typeof forecast>){const d=rows.filter(r=>r.type==='DRIVER');return {...score(rows),positionsMAE:mean(d.map(r=>Math.abs(r.components.positions-r.observed.race!.positionChange))),overtakesMAE:mean(d.map(r=>Math.abs(r.components.overtakes-r.observed.race!.overtakes))),qualifyingMAE:mean(d.map(r=>Math.abs(r.components.qualifying-r.observed.qualifying!.total)))}}
async function main(){
 const development=[6,7,8,9,10,11],later=[12,13,14,15,16];const current:Candidate={name:'current',gridRelative:false,conditional:false,reliability:false};const previous:Candidate={name:'historical-race-pace',gridRelative:false,raceNoise:.15,conditional:false,reliability:false};
 const base=summarize(development.flatMap(round=>predict(round,current)));const candidates:any[]=[];
 for(const qualifyingNoise of [undefined,.15,.3])for(const raceNoise of [0,.05,.15,.3,.5])for(const conditional of [false,true])for(const reliability of [false,true]){const c:Candidate={name:'grid-relative-progress',gridRelative:true,raceNoise,qualifyingNoise,conditional,reliability};const s=summarize(development.flatMap(round=>predict(round,c)));const eligible=s.DRIVER.MAE<=base.DRIVER.MAE&&s.CONSTRUCTOR.MAE<=base.CONSTRUCTOR.MAE&&s.positionsMAE<=base.positionsMAE&&s.overtakesMAE<=base.overtakesMAE;candidates.push({...c,...s,eligible})}
 candidates.sort((a,b)=>a.objective-b.objective);const eligible=candidates.filter(c=>c.eligible);const selected:Candidate=eligible[0]??current,bestAggregate:Candidate=candidates[0];
 const report:any={note:'Exploratory on previously inspected rounds. Selection uses only rounds 6–11. Eligibility requires no worse driver/constructor weekend MAE, position-change MAE and overtake MAE on development. No production activation.',developmentRounds:development,evaluationRounds:later,baselineDevelopment:base,eligibleCount:eligible.length,selected,bestAggregate,candidates,metrics:[],byRound:[]};
 for(const [segment,rounds] of [['development',development],['previously-inspected',later]] as const)for(const [model,c] of [['current',current],['previous-race-pace',previous],['selected-with-component-gate',selected],['best-aggregate-diagnostic',bestAggregate]] as const){const rows=rounds.flatMap(round=>predict(round,c));const s=summarize(rows);for(const type of ['DRIVER','CONSTRUCTOR'] as const)report.metrics.push({segment,model,type,...s[type],...(type==='DRIVER'?{positionsMAE:s.positionsMAE,overtakesMAE:s.overtakesMAE,qualifyingMAE:s.qualifyingMAE}:{})});for(const round of rounds)report.byRound.push({segment,model,round,...summarize(rows.filter(r=>r.round===round))})}
 console.log('Eligible candidates:',eligible.length);console.table(candidates.slice(0,12).map(c=>({qNoise:c.qualifyingNoise,rNoise:c.raceNoise,conditional:c.conditional,reliability:c.reliability,eligible:c.eligible,driverMAE:c.DRIVER.MAE,constructorMAE:c.CONSTRUCTOR.MAE,positionsMAE:c.positionsMAE,overtakesMAE:c.overtakesMAE})));console.table(report.metrics);await writeFile('docs/race-progress-results.json',JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1});
