import {chromium} from 'playwright';import {readFileSync} from 'node:fs';import ts from 'typescript';import assert from 'node:assert/strict';import {f1TeamBookmarklet} from '../src/lib/f1-team-browser-helper';
async function main(){const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});try{
 const context=await browser.newContext();const source=ts.transpile(readFileSync('src/lib/f1-direct-transfer.ts','utf8'),{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.ESNext}).replaceAll('export function ','function ');
 await context.addInitScript({content:source+';window.installTransfer=receiveF1Transfer;'});
 await context.route('https://paddock.test/**',route=>route.fulfill({contentType:'text/html',body:'<html><body><p id="status">Waiting</p><script>window.installTransfer(window,p=>{window.received=p;document.getElementById("status").textContent="Received"},e=>{document.getElementById("status").textContent=e})</script></body></html>'}));
 await context.route('https://fantasy.formula1.com/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/en/')return route.fulfill({contentType:'text/html',body:'<html><body><a id="send">Send</a></body></html>'});return route.fulfill({json:{Data:{Value:path.includes('/schedule/')?[{MatchStatus:1,GamedayId:17,PhaseId:1,Season:2026}]:path.includes('/getteam/')?{mdid:17,userTeam:[{teamno:1,teamname:'Browser team',playerid:[],token:'must-not-leak',GUID:'must-not-leak'}]}:[]}}})});
 const f1=await context.newPage();const alerts:string[]=[];f1.on('dialog',async d=>{alerts.push(d.message());await d.dismiss()});await f1.goto('https://fantasy.formula1.com/en/');await f1.evaluate(()=>fetch('/services/user/gameplay/private/getteam/0/0/17/1'));
 await f1.locator('#send').evaluate((a,href)=>a.setAttribute('href',href),f1TeamBookmarklet('https://paddock.test'));
 const [popup]=await Promise.all([context.waitForEvent('page'),f1.locator('#send').click()]);await popup.waitForFunction(()=>Boolean((window as any).received));const received=await popup.evaluate(()=>(window as any).received);assert.equal(received.teams[0].teamname,'Browser team');assert.ok(!JSON.stringify(received).includes('must-not-leak'));assert.equal(new URL(popup.url()).hash,'');assert.equal(await popup.evaluate(()=>window.opener),null);assert.deepEqual(alerts,[]);console.log('Cross-origin browser transfer passed: sanitized payload, exact receiver, cleared nonce and detached opener.');
 }finally{await browser.close()}}
main().catch(e=>{console.error(e);process.exitCode=1});
