import assert from 'node:assert/strict';
import {test} from 'node:test';
import prices from '../src/data/fantasy-prices-2025.json';
import {normalizeFantasyPriceArchive} from '../src/lib/fantasy-price-archive';
function fixture(){const raceResults:Record<string,any>={};for(let round=1;round<=24;round++){const rows=prices.observations.filter(r=>r.round===round);raceResults[round]={drivers:rows.filter(r=>r.type==='DRIVER').map(r=>({id:r.team+'_'+r.code,abbreviation:r.code,constructorId:r.team,isActive:true,price:r.priceBefore,totalPoints:99999,priceChange:99999})),constructors:rows.filter(r=>r.type==='CONSTRUCTOR').map(r=>({id:r.code,abbreviation:r.code,price:r.priceBefore,totalPoints:99999,priceChange:99999}))}}return {seasonResult:{season:2025,raceResults}}}
test('price extraction excludes outcome totals and subsequent price changes',()=>{const result=normalizeFantasyPriceArchive(fixture());assert.equal(result.length,720);assert.ok(result.every(r=>Object.keys(r).sort().join(',')==='code,priceBefore,round,team,type'))});
test('missing rounds, wrong seasons, empty and nonfinite quotes are rejected',()=>{const wrong=fixture();wrong.seasonResult.season=2026;assert.throws(()=>normalizeFantasyPriceArchive(wrong));const missing=fixture();delete missing.seasonResult.raceResults['9'];assert.throws(()=>normalizeFantasyPriceArchive(missing));for(const price of [0,NaN,null,'7.5']){const invalid=fixture();invalid.seasonResult.raceResults['1'].drivers[0].price=price;assert.throws(()=>normalizeFantasyPriceArchive(invalid))}});
test('duplicate active identities and incomplete constructor pairs are rejected',()=>{const duplicate=fixture();duplicate.seasonResult.raceResults['1'].drivers[1]=duplicate.seasonResult.raceResults['1'].drivers[0];assert.throws(()=>normalizeFantasyPriceArchive(duplicate));const mismatched=fixture();mismatched.seasonResult.raceResults['1'].drivers[0].constructorId='other';assert.throws(()=>normalizeFantasyPriceArchive(mismatched))});
test('inactive alternate seat identities are excluded from the price roster',()=>{const data=fixture();data.seasonResult.raceResults['1'].drivers.push({...data.seasonResult.raceResults['1'].drivers[0],isActive:false});assert.equal(normalizeFantasyPriceArchive(data).length,720)});
