import {test} from 'node:test';import assert from 'node:assert/strict';import {runInNewContext} from 'node:vm';import {f1TeamBookmarklet} from '../src/lib/f1-team-browser-helper';import {isF1TransferMessage} from '../src/lib/f1-direct-transfer';
const nonce='12345678-1234-1234-1234-123456789abc';
test('receiver accepts only the expected F1 window, nonce and bounded payload',()=>{const opener={},payload={format:'paddock-iq-f1-v1'};const event={origin:'https://fantasy.formula1.com',source:opener,data:{type:'PADDOCK_F1_PAYLOAD',nonce,payload}};assert.equal(isF1TransferMessage(event,opener,nonce),true);for(const e of [{...event,origin:'https://evil.test'},{...event,source:{}},{...event,data:{...event.data,nonce:'other'}},{...event,data:{...event.data,payload:{format:'other'}}},{...event,data:{...event.data,payload:{...payload,large:'x'.repeat(100001)}}}])assert.equal(isF1TransferMessage(e,opener,nonce),false);assert.equal(isF1TransferMessage(event,null,nonce),false)});
test('bookmark opens synchronously and sends only sanitized lineup to its exact destination after handshake',async()=>{let handler:any,opened=false;const messages:any[]=[];const popup={postMessage:(data:any,origin:string)=>messages.push({data,origin}),focus(){}};const origin='https://paddock.test';const context={location:{origin:'https://fantasy.formula1.com'},performance:{getEntriesByType:()=>[{name:'https://fantasy.formula1.com/services/user/gameplay/private/getteam/0/0/17/1'}]},URL,crypto:{randomUUID:()=>nonce},AbortSignal,Date,setTimeout:()=>1,clearTimeout(){},alert:(m:string)=>{throw Error(m)},window:{open:(url:string)=>{assert.equal(url,origin+'/team/import#f1-transfer='+nonce);opened=true;return popup},addEventListener:(_:string,h:any)=>{handler=h},removeEventListener(){}},fetch:async(url:string)=>{assert.ok(opened);assert.equal(new URL(url).origin,'https://fantasy.formula1.com');return {ok:true,json:async()=>({Data:{Value:url.includes('/schedule/')?[{MatchStatus:1,GamedayId:17,PhaseId:1,Season:2026}]:url.includes('/getteam/')?{mdid:17,userTeam:[{teamno:1,teamname:'Mine',playerid:[],token:'secret',GUID:'secret'}]}:[]}})}}};await runInNewContext(f1TeamBookmarklet(origin).replace('javascript:void ',''),context);assert.equal(messages.length,0);handler({origin:'https://evil.test',source:popup,data:{type:'PADDOCK_F1_READY',nonce}});assert.equal(messages.length,0);handler({origin,source:popup,data:{type:'PADDOCK_F1_READY',nonce}});assert.equal(messages.length,1);assert.equal(messages[0].origin,origin);assert.ok(!JSON.stringify(messages[0]).includes('secret'));handler({origin,source:popup,data:{type:'PADDOCK_F1_ACK',nonce}});handler({origin,source:popup,data:{type:'PADDOCK_F1_READY',nonce}});assert.equal(messages.length,1)});
test('destination rejects insecure remote URLs and credentials',()=>{for(const url of ['http://remote.test','https://user:pass@paddock.test','javascript:alert(1)'])assert.throws(()=>f1TeamBookmarklet(url));assert.ok(f1TeamBookmarklet('http://localhost:3000').startsWith('javascript:'))});

import {receiveF1Transfer} from '../src/lib/f1-direct-transfer';
test('receiver consumes once and expires without accepting late messages',()=>{for(const expire of [false,true]){let listener:any,timeout:any,received=0,errors=0,removed=0;const sent:any[]=[];const opener={postMessage:(data:any,origin:string)=>sent.push({data,origin})};const win:any={opener,location:{hash:'#f1-transfer='+nonce,pathname:'/team/import',search:''},history:{replaceState:()=>{}},addEventListener:(_:string,f:any)=>listener=f,removeEventListener:()=>removed++,setInterval:()=>1,clearInterval:()=>{},setTimeout:(f:any)=>{timeout=f;return 2},clearTimeout:()=>{}};receiveF1Transfer(win,()=>received++,()=>errors++);assert.equal(sent[0].origin,'https://fantasy.formula1.com');if(expire)timeout();const event={origin:'https://fantasy.formula1.com',source:opener,data:{type:'PADDOCK_F1_PAYLOAD',nonce,payload:{format:'paddock-iq-f1-v1'}}};listener(event);listener(event);assert.equal(received,expire?0:1);assert.equal(errors,expire?1:0);assert.equal(removed,1)}});
test('blocked popup aborts before reading private team data',async()=>{let reads=0,message='';await runInNewContext(f1TeamBookmarklet('https://paddock.test').replace('javascript:void ',''),{location:{origin:'https://fantasy.formula1.com'},performance:{getEntriesByType:()=>[{name:'https://fantasy.formula1.com/services/user/gameplay/private/getteam/0/0/17/1'}]},URL,crypto:{randomUUID:()=>nonce},window:{open:()=>null},fetch:()=>reads++,alert:(m:string)=>message=m,Error});assert.equal(reads,0);assert.match(message,/Allow pop-ups/)});
