import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {normalizeF1TeamExport} from '../src/lib/f1-team-import';
import {readFile} from 'node:fs/promises';
async function main(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
 try{
 const market=[...['VER','NOR','LEC','ANT','PIA'].map(code=>({code,name:code,type:'DRIVER' as const})),{code:'MER',name:'Mercedes',type:'CONSTRUCTOR' as const},{code:'RBR',name:'Red Bull Racing',type:'CONSTRUCTOR' as const}];
 const players=market.map((a,i)=>({PlayerId:String(i+1),DriverTLA:a.type==='DRIVER'?a.code:'',TeamName:a.name,PositionName:a.type}));
 const rawTeam={teamno:1,teamname:'Race%20Team',playerid:players.map(p=>({id:p.PlayerId})),capplayerid:'1',team_info:{teamBal:0,userSubsleft:2,subsallowed:2},usersubsleft:0,ovpoints:-5};
 const apiPage=await browser.newPage();const helperResponse=await apiPage.request.get(new URL('/api/team/f1/helper',process.env.PADDOCK_TEST_URL||'http://localhost:3100/team/import').href);assert.ok(helperResponse.ok());const actualHelper=(await helperResponse.json()).bookmarklet;await apiPage.close();
 const f1=await browser.newPage({acceptDownloads:true});
 await f1.route('https://fantasy.formula1.com/**',async route=>{const path=new URL(route.request().url()).pathname;const value=path.includes('/schedule/')?[{GamedayId:18,PhaseId:1,Season:'2026',MatchStatus:'1'}]:path.includes('/getteam/')?{mdid:18,userTeam:[{...rawTeam,GUID:'private',token:'private'},{...rawTeam,teamno:2,teamname:'Second',capplayerid:'2',team_info:{teamBal:0.4,userSubsleft:3},ovpoints:100}]}:players;await route.fulfill({contentType:path==='/en/'?'text/html':'application/json',body:path==='/en/'?'<html><body>F1 fixture</body></html>':JSON.stringify({Meta:{Success:true},Data:{Value:value}})})});
 await f1.goto('https://fantasy.formula1.com/en/');await f1.evaluate(()=>fetch('/services/user/gameplay/private/getteam/0/1/17/1'));
 await f1.evaluate(source=>{const a=document.createElement('a');a.setAttribute('href',source);a.id='export';a.textContent='Export';document.body.appendChild(a)},actualHelper);
 f1.on('dialog',dialog=>void dialog.dismiss());
 const [download]=await Promise.all([f1.waitForEvent('download'),f1.locator('#export').click()]);
 const exported=JSON.parse(await readFile((await download.path())!,'utf8'));assert.ok(!JSON.stringify(exported).includes('private'));const normalized=normalizeF1TeamExport(exported,market,2026,18);assert.equal(normalized.teams[0].freeTransfers,2);
 if(!process.env.PADDOCK_TEST_STORAGE_STATE)throw Error('Set PADDOCK_TEST_STORAGE_STATE to a signed-in test-account Playwright storage state.');
 const page=await browser.newPage({storageState:process.env.PADDOCK_TEST_STORAGE_STATE});let saved:any;
 await page.route('**/api/account',route=>route.fulfill({json:{user:{id:'ui-owner',email:'other@example.test'}}}));
 await page.route('**/api/market?*',route=>route.fulfill({json:{assets:market}}));
 await page.route('**/api/team/f1/import',async route=>{const body=route.request().postDataJSON();if(body.action==='save'){saved=body;await route.fulfill({json:{ok:true,snapshotId:'ui-snapshot',teamId:'ui-team',teams:[{teamNo:1,teamId:'ui-team'},{teamNo:2,teamId:'ui-other'}]}})}else await route.fulfill({json:normalized})});
 await page.goto(process.env.PADDOCK_TEST_URL||'http://localhost:3100/team/import');
 await page.getByLabel('F1 team export').setInputFiles({name:'f1-team.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
 await page.getByRole('button',{name:'Preview F1 team'}).click();await page.getByRole('heading',{name:'Race Team'}).waitFor();assert.match(await page.locator('main').innerText(),/VER · Driver · 2×/);
 assert.equal(await page.getByRole('button',{name:'Save all 2 teams'}).count(),1);
 assert.equal(await page.getByLabel('Paddock IQ profile email').count(),0);await page.getByRole('button',{name:'Save all 2 teams'}).click();await page.getByRole('status').filter({hasText:'2 teams saved.'}).waitFor();assert.equal(saved.teamNo,1);assert.equal(saved.season,2026);assert.equal(saved.round,18);
 await page.reload();await page.getByLabel('F1 team export').setInputFiles({name:'f1-team.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.getByRole('button',{name:'Preview F1 team'}).click();await page.getByRole('heading',{name:'Race Team'}).waitFor();assert.equal(await page.getByLabel('Paddock IQ profile email').count(),0);await page.getByRole('button',{name:'Save all 2 teams'}).click();await page.getByRole('status').filter({hasText:'2 teams saved.'}).waitFor();assert.equal(saved.email,undefined);
 await page.getByText('Manual setup (fallback)',{exact:true}).click();await page.getByRole('button',{name:'Save team',exact:true}).waitFor({state:'visible'});
 const details:Record<string,any>={'ui-team':{name:'Race Team',cashBalance:0,freeTransfers:2,totalPoints:-5,assets:normalized.teams[0].assets},'ui-other':{name:'Second',cashBalance:0.4,freeTransfers:3,totalPoints:100,assets:normalized.teams[1].assets}};
 let requestedTeam='';let deleteRequests=0;let edited:any;
 await page.route('**/api/team?*',async route=>{requestedTeam=route.request().url();const id=new URL(requestedTeam).searchParams.get('teamId')||Object.keys(details)[0];const d=details[id];if(!d){await route.fulfill({status:404,json:{error:'No team found'}});return}await route.fulfill({json:{user:{email:'other@example.test',name:null},teams:Object.entries(details).map(([id,d])=>({id,name:d.name})),team:{id,name:d.name,season:2026},snapshot:{id:'snapshot-'+id,capturedAt:new Date().toISOString(),grandPrix:{round:18,name:'Round 18'},cashBalance:d.cashBalance,freeTransfers:d.freeTransfers,totalPoints:d.totalPoints,assets:d.assets.map((a:any)=>({...market.find(m=>m.code===a.code),...a,price:1,expectedPoints:1,expectedDelta:0,recentFantasyScores:[]})),chips:[]}}})});
 await page.route('**/api/team/manage',async route=>{const b=route.request().postDataJSON();assert.equal(b.email,undefined);if(route.request().method()==='PATCH'){edited=b;details[b.teamId]={...details[b.teamId],...b};await route.fulfill({json:{ok:true,teamId:b.teamId}})}else{deleteRequests++;delete details[b.teamId];await route.fulfill({json:{ok:true,season:2026,teams:Object.entries(details).map(([id,d])=>({id,name:d.name}))}})}});
 await page.goto(new URL('/my-team',process.env.PADDOCK_TEST_URL||'http://localhost:3100/team/import').href);await page.getByText('Free transfers',{exact:true}).waitFor();assert.equal(new URL(requestedTeam).searchParams.get('email'),null);assert.equal(new URL(requestedTeam).searchParams.get('teamId'),'ui-team');assert.equal(await page.getByText('Free transfers',{exact:true}).locator('..').locator('strong').innerText(),'2');
 await page.getByLabel('Your teams').selectOption('ui-other');await page.getByRole('heading',{name:'Second · 2026',exact:true}).waitFor();assert.equal(new URL(requestedTeam).searchParams.get('teamId'),'ui-other');assert.equal(await page.getByText('Free transfers',{exact:true}).locator('..').locator('strong').innerText(),'3');await page.reload();await page.getByRole('heading',{name:'Second · 2026',exact:true}).waitFor();assert.equal(await page.getByLabel('Your teams').inputValue(),'ui-other');
 assert.equal(await page.getByRole('button',{name:'Edit team',exact:true}).count(),1);let releasePrediction!:()=>void;let predictionStarted!:()=>void;const predictionGate=new Promise<void>(resolve=>{releasePrediction=resolve}),predictionReady=new Promise<void>(resolve=>{predictionStarted=resolve});await page.route('**/api/predictions/auto',async route=>{predictionStarted();await predictionGate;await route.fulfill({json:{created:1}})});await page.getByRole('button',{name:'Generate / refresh xPts + price probabilities'}).click();await predictionReady;await page.getByRole('button',{name:'Edit team',exact:true}).click();await page.getByLabel('Team name',{exact:true}).fill('Edited Second');const predictionResponse=page.waitForResponse('**/api/predictions/auto');releasePrediction();await (await predictionResponse).finished();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await page.getByLabel('Team name',{exact:true}).count(),1);assert.equal(await page.getByLabel('Team name',{exact:true}).inputValue(),'Edited Second');await page.getByLabel('Free transfers',{exact:true}).fill('1');await page.getByLabel('2× driver',{exact:true}).selectOption('ANT');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('heading',{name:'Edited Second · 2026',exact:true}).waitFor();assert.equal(edited.teamId,'ui-other');assert.equal(edited.freeTransfers,1);assert.deepEqual(edited.assets.filter((a:any)=>a.isDoubled).map((a:any)=>a.code),['ANT']);assert.equal(await page.getByLabel('Your teams').inputValue(),'ui-other');
 page.once('dialog',dialog=>void dialog.dismiss());await page.getByRole('button',{name:'Delete team',exact:true}).click();assert.equal(deleteRequests,0);
 page.once('dialog',dialog=>void dialog.accept());await page.getByRole('button',{name:'Delete team',exact:true}).click();await page.getByRole('heading',{name:'Race Team · 2026',exact:true}).waitFor();assert.equal(await page.getByLabel('Your teams').inputValue(),'ui-team');assert.equal(Object.keys(details).length,1);
 page.once('dialog',dialog=>void dialog.accept());await page.getByRole('button',{name:'Delete team',exact:true}).click();await page.getByText('Team deleted. No teams left for this profile.',{exact:true}).waitFor();assert.equal(Object.keys(details).length,0);
 console.log('Import, profile/team switching, editing, confirmed deletion and unsaved-edit protection passed.');
 }finally{await browser.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
