import assert from 'node:assert/strict';
import {test} from 'node:test';
import {parseFantasyToolsComponents} from '../src/lib/fantasy-tools-components';
const stat=(points:number)=>({points});
const q={positionPoints:stat(8),notClassifiedPoints:stat(0),disqualifiedPoints:stat(0),teamworkPoints:stat(0),totalPoints:stat(8)};
const race={positionPoints:stat(18),notClassifiedPoints:stat(0),disqualifiedPoints:stat(0),fastestLapPoints:stat(0),overtakes:stat(2),positionsGained:stat(1),dotdPoints:stat(0),fastestPitStopPoints:stat(0),overallFastestPitStopPoints:stat(0),worldRecordPitStopPoints:stat(0),totalPoints:stat(21)};
const driver={id:'RED_VER',abbreviation:'VER',constructorId:'RED',isActive:true,price:28,totalPoints:29,qualifyingPosition:'3',racePosition:'2',raceResult:{Q:q,R:race}};
const source=(rows:any[])=>({seasonResult:{season:2025,raceResults:{'1':{drivers:rows,constructors:[]}}}});
test('actual scoring components and historical identity are retained',()=>{const row=parseFantasyToolsComponents(source([driver]),1)[0];assert.equal(row.code,'VER');assert.equal(row.team,'RBR');assert.equal(row.actualPoints,29);assert.deepEqual(row.race,{total:21,failed:false,disqualified:false,overtakes:2,fastestLap:false,dotd:false,finishPosition:2,positionChange:1})});
test('negative lost-position totals are not failures',()=>{const r={...race,positionPoints:stat(0),overtakes:stat(2),positionsGained:stat(-12),totalPoints:stat(-10)};const row=parseFantasyToolsComponents(source([{...driver,racePosition:'14',totalPoints:-2,raceResult:{Q:q,R:r}}]),1)[0];assert.equal(row.race?.failed,false);assert.equal(row.race?.positionChange,-12)});
test('explicit NC retains earned overtakes and explicit DSQ is a Fantasy failure',()=>{for(const key of ['notClassifiedPoints','disqualifiedPoints']){const r={...race,positionPoints:stat(0),positionsGained:stat(0),overtakes:stat(3),[key]:stat(-20),totalPoints:stat(-17)};const row=parseFantasyToolsComponents(source([{...driver,racePosition:'NC',totalPoints:-9,raceResult:{Q:q,R:r}}]),1)[0];assert.equal(row.race?.failed,true);assert.equal(row.race?.overtakes,3)}});
test('inactive alternate IDs and future component outcomes are excluded',()=>{const payload=source([driver,{...driver,id:'VRB_VER',constructorId:'VRB',isActive:false}]) as any;payload.seasonResult.raceResults['2']={drivers:[{...driver,totalPoints:99999}],constructors:[]};assert.equal(parseFantasyToolsComponents(payload,1).length,1)});
test('inconsistent component totals and ambiguous active identities are rejected',()=>{assert.throws(()=>parseFantasyToolsComponents(source([{...driver,totalPoints:30}]),1));assert.throws(()=>parseFantasyToolsComponents(source([driver,{...driver,id:'VRB_VER',constructorId:'VRB'}]),1))});
test('missing positions do not fabricate successful race observations',()=>assert.throws(()=>parseFantasyToolsComponents(source([{...driver,racePosition:null}]),1)));
test('wrong season and missing session totals are rejected',()=>{const payload=source([driver]);payload.seasonResult.season=2026;assert.throws(()=>parseFantasyToolsComponents(payload,1));assert.throws(()=>parseFantasyToolsComponents(source([{...driver,raceResult:{Q:q,R:{...race,totalPoints:undefined}}}]),1))});

import components from '../src/data/component-history-2025.json';
import {qualifyingDriverPoints,raceDriverPoints,sprintDriverPoints} from '../src/lib/fantasy-scoring';
test('all archived driver session components reproduce their reported scoring totals',()=>{for(const row of components.observations.filter(r=>r.type==='DRIVER')){assert.equal(qualifyingDriverPoints({position:row.qualifying.position,noTime:row.qualifying.noTime}),row.qualifying.total,row.code+' R'+row.round+' Q');const race=row.race;assert.equal(raceDriverPoints({startPosition:race.finishPosition==null?null:race.finishPosition+race.positionChange,finishPosition:race.finishPosition,classified:!race.failed,overtakes:race.overtakes,fastestLap:race.fastestLap,driverOfTheDay:race.dotd}),race.total,row.code+' R'+row.round+' R');if(row.sprint){const s=row.sprint;assert.equal(sprintDriverPoints({season:row.season,startPosition:s.finishPosition==null?null:s.finishPosition+s.positionChange,finishPosition:s.finishPosition,classified:!s.failed,overtakes:s.overtakes,fastestLap:s.fastestLap}),s.total,row.code+' R'+row.round+' S')}}});

test('historical Sprint NC uses the 2025 penalty while current defaults stay 2026',()=>{const failed={startPosition:2,finishPosition:null,classified:false,overtakes:2};assert.equal(sprintDriverPoints({...failed,season:2025}),-18);assert.equal(sprintDriverPoints({...failed,season:2026}),-8);assert.equal(sprintDriverPoints(failed),-8)});

test('constructor pit awards are conserved without inferring stop seconds',()=>{const constructor={id:'MCL',abbreviation:'MCL',price:31,totalPoints:64,raceResult:{Q:{...q,positionPoints:stat(19),teamworkPoints:stat(10),totalPoints:stat(29)},R:{...race,positionPoints:stat(20),overtakes:stat(0),positionsGained:stat(0),fastestPitStopPoints:stat(5),overallFastestPitStopPoints:stat(10),totalPoints:stat(35)}}};const payload=source([]) as any;payload.seasonResult.raceResults['1'].constructors=[constructor];assert.equal(parseFantasyToolsComponents(payload,1)[0].pitPoints,15)});

import {constructorQualifyingPoints,constructorSprintPoints,constructorRacePoints} from '../src/lib/fantasy-scoring';
test('constructor sessions match their two drivers and explicit pit awards',()=>{const errors:any[]=[];for(const c of components.observations.filter(r=>r.type==='CONSTRUCTOR')){const ds=components.observations.filter(r=>r.round===c.round&&r.type==='DRIVER'&&r.team===c.code);assert.equal(ds.length,2);const q2=ds.filter(d=>!d.qualifying.noTime&&d.qualifying.position!=null&&d.qualifying.position<=15).length,q3=ds.filter(d=>!d.qualifying.noTime&&d.qualifying.position!=null&&d.qualifying.position<=10).length;const q=constructorQualifyingPoints([ds[0].qualifying.total,ds[1].qualifying.total],q2,q3);if(q!==c.qualifying.total)errors.push({code:c.code,round:c.round,phase:'Q',replay:q,reported:c.qualifying.total});const driverPoints=ds.map(d=>d.race.total-Number(d.race.dotd)*10) as [number,number],dsq=ds.filter(d=>d.race.disqualified).length;const race=constructorRacePoints({season:c.season,driverRacePointsExcludingDotD:driverPoints,bestPitStopSeconds:null,dsqDrivers:dsq})+(c.pitPoints??0);if(race!==c.race.total)errors.push({code:c.code,round:c.round,phase:'R',replay:race,reported:c.race.total});if(c.sprint){const sprint=constructorSprintPoints([ds[0].sprint!.total,ds[1].sprint!.total]);if(sprint!==c.sprint.total)errors.push({code:c.code,round:c.round,phase:'S',replay:sprint,reported:c.sprint.total})}}assert.deepEqual(errors,[])});

test('constructor DSQ extra penalty is season-specific beyond already scored driver totals',()=>{const input={driverRacePointsExcludingDotD:[-20,0] as [number,number],bestPitStopSeconds:null,dsqDrivers:1};assert.equal(constructorRacePoints({...input,season:2025}),-30);assert.equal(constructorRacePoints({...input,season:2026}),-40)});
