import assert from 'node:assert/strict';
import {test,mock} from 'node:test';
import {getPracticeSnapshot,type OpenF1Session} from '../src/lib/openf1-weekend';
const make=(key:number,name:string,start:string,end:string):OpenF1Session=>({year:2026,meeting_key:10,session_key:key,session_name:name,session_type:name,date_start:start,date_end:end});
const sessions=[make(1,'Practice 1','2026-10-09T09:00:00Z','2026-10-09T10:00:00Z'),make(2,'Sprint Qualifying','2026-10-09T13:00:00Z','2026-10-09T14:00:00Z'),make(3,'Sprint','2026-10-10T09:00:00Z','2026-10-10T10:00:00Z')];
async function snapshot(asOf:string){const requested:string[]=[];const m=mock.method(globalThis,'fetch',async(input:any)=>{const u=String(input);requested.push(u);const value=u.includes('/sessions?')?sessions:u.includes('/drivers?')?[{driver_number:1,name_acronym:'VER'},{driver_number:4,name_acronym:'NOR'}]:u.includes('session_key=1')?[{driver_number:1,position:2},{driver_number:4,position:1}]:u.includes('session_key=2')?[{driver_number:1,position:1},{driver_number:4,position:2}]:[];return new Response(JSON.stringify(value))});try{return {value:await getPracticeSnapshot(2026,new Date('2026-10-10T09:00:00Z'),new Date(asOf)),requested}}finally{m.mock.restore()}}
test('sprint FP1 and SQ are separate pre-lock signals',async()=>{const {value}=await snapshot('2026-10-09T15:00:00Z');assert.equal(value?.positions.get('VER'),2);assert.equal(value?.sprintQualifyingPositions?.get('VER'),1);assert.equal(value?.sessionKey,1)});
test('ongoing SQ cannot enter while completed FP1 remains usable',async()=>{const {value,requested}=await snapshot('2026-10-09T13:30:00Z');assert.equal(value?.positions.get('VER'),2);assert.equal(value?.sprintQualifyingPositions?.size??0,0);assert.ok(!requested.some(u=>u.includes('/session_result?session_key=2')))});
import {getWeekendLock} from '../src/lib/openf1-weekend';
test('missing database lock resolves to sprint start with calendar/provider agreement',async()=>{const race=make(4,'Race','2026-10-11T12:00:00Z','2026-10-11T14:00:00Z');const m=mock.method(globalThis,'fetch',async(input:any)=>new Response(JSON.stringify(String(input).includes('f1fantasytools')?{races:[{roundNumber:17,name:'Singapore Grand Prix',sprint:true,start_times:{race:race.date_start,sprint:sessions[2].date_start}}]}:[...sessions,race])));try{const result=await getWeekendLock(2026,17,'Singapore GP',null);assert.equal(result?.deadline.toISOString(),'2026-10-10T09:00:00.000Z');assert.equal(result?.isSprint,true)}finally{m.mock.restore()}});
